/-
Copyright (c) 2026 Egor Lyfar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Egor Lyfar
-/
import GKPCarry

#print axioms GKPCarry.sub_one_mul_padicValNat_centralBinom
#print axioms GKPCarry.padicValNat_two_centralBinom
#print axioms GKPCarry.gkpConjecture_iff_powerOfTwo
#print axioms GKPCarry.ternaryDigitExcess_eq_two_mul_ternaryDoubleCarryCount
#print axioms GKPCarry.nine_dvd_centralBinom_iff_two_le_ternaryDoubleCarryCount
#print axioms GKPCarry.badCarryLanguage_true_iff_carryCount_lt_two
#print axioms GKPCarry.badCarryLanguage_true_iff_shape
#print axioms GKPCarry.card_badCarryWords
#print axioms GKPCarry.gkpConjecture_iff_badCarryLanguageExclusion
#print axioms GKPCarry.powModDigits_eq_pow_mod
#print axioms GKPCarry.powMod_eq_pow_mod
#print axioms GKPCarry.hasTwoTernaryTwosBelow_iff_mod
#print axioms GKPCarry.four_pow_has_two_ternary_twos_in_finite_range
#print axioms GKPCarry.four_pow_has_two_ternary_twos_of_length_le_eight
#print axioms GKPCarry.four_pow_prefix_carry_count_ge_two_in_finite_range
#print axioms GKPCarry.nine_dvd_centralBinom_four_pow_in_finite_range
#print axioms GKPCarry.padicValNat_oddPrime_centralBinom_ofDigits_eq_carryCount
#print axioms GKPCarry.oddPrimeValuationPolynomial_eq_carryPolynomial
#print axioms GKPCarry.oddPrimeValuationPolynomial_recurrence
#print axioms GKPCarry.oddPrimeValuationGeneratingSeries_identity
#print axioms GKPCarry.card_oddPrimeBlock_valuation_zero
#print axioms GKPCarry.card_oddPrimeBlock_valuation_one
#print axioms GKPCarry.card_ternaryBlock_valuation_lt_two
