/-
Copyright (c) 2026 Egor Lyfar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Egor Lyfar
-/
import GKPCarry.BinaryReduction
import GKPCarry.Definitions
import Lean.Elab.Tactic.Omega
import Mathlib.Data.Nat.Digits.Lemmas
import Mathlib.Tactic.IntervalCases

/-!
# Arithmetic correctness of the ternary doubling transducer

The transducer in `GKPCarry.Definitions` counts outgoing carries while doubling
a little-endian ternary word.  This file proves that, on the canonical ternary
digits of `n`, twice that count is exactly Kummer's ternary digit excess.
-/

namespace GKPCarry

open Nat

/-- Kummer's ternary digit excess for a central binomial coefficient. -/
def ternaryDigitExcess (n : ℕ) : ℕ :=
  2 * (Nat.digits 3 n).sum - (Nat.digits 3 (2 * n)).sum

/-- Fixed-length output digits emitted while doubling a ternary word.  The
final carry is retained as the last digit. -/
def ternaryDoubleDigitsAux : List ℕ → ℕ → List ℕ
  | [], carry => [carry]
  | digit :: digits, carry =>
      ((2 * digit + carry) % 3) ::
        ternaryDoubleDigitsAux digits (ternaryDoubleCarryStep carry digit)

lemma ternaryDoubleCarryStep_le_one (carry digit : ℕ) :
    ternaryDoubleCarryStep carry digit ≤ 1 := by
  unfold ternaryDoubleCarryStep
  split <;> omega

lemma ternaryDoubleCarryStep_lt_three (carry digit : ℕ) :
    ternaryDoubleCarryStep carry digit < 3 := by
  have := ternaryDoubleCarryStep_le_one carry digit
  omega

lemma ternaryDoubleCarryStep_eq_div
    {carry digit : ℕ} (hcarry : carry ≤ 1) (hdigit : digit < 3) :
    ternaryDoubleCarryStep carry digit = (2 * digit + carry) / 3 := by
  interval_cases digit <;> interval_cases carry <;> decide

lemma ternaryDoubleCarryStep_local
    {carry digit : ℕ} (hcarry : carry ≤ 1) (hdigit : digit < 3) :
    (2 * digit + carry) % 3 + 3 * ternaryDoubleCarryStep carry digit =
      2 * digit + carry := by
  rw [ternaryDoubleCarryStep_eq_div hcarry hdigit]
  exact Nat.mod_add_div (2 * digit + carry) 3

lemma ternaryDoubleDigitsAux_length (digits : List ℕ) (carry : ℕ) :
    (ternaryDoubleDigitsAux digits carry).length = digits.length + 1 := by
  induction digits generalizing carry with
  | nil => simp [ternaryDoubleDigitsAux]
  | cons digit digits ih => simp [ternaryDoubleDigitsAux, ih, Nat.add_assoc]

lemma ternaryDoubleDigitsAux_lt_three
    {digits : List ℕ} {carry : ℕ} (hcarry : carry < 3)
    (hdigits : ∀ digit ∈ digits, digit < 3) :
    ∀ value ∈ ternaryDoubleDigitsAux digits carry, value < 3 := by
  induction digits generalizing carry with
  | nil => simpa [ternaryDoubleDigitsAux]
  | cons digit digits ih =>
      intro value hvalue
      rw [ternaryDoubleDigitsAux] at hvalue
      rcases List.mem_cons.mp hvalue with rfl | htail
      · exact Nat.mod_lt _ (by decide)
      · apply ih (ternaryDoubleCarryStep_lt_three carry digit)
          (fun d hd => hdigits d (List.mem_cons_of_mem digit hd))
          value htail

lemma ternaryDoubleDigitsAux_ofDigits
    {digits : List ℕ} {carry : ℕ} (hcarry : carry ≤ 1)
    (hdigits : ∀ digit ∈ digits, digit < 3) :
    Nat.ofDigits 3 (ternaryDoubleDigitsAux digits carry) =
      2 * Nat.ofDigits 3 digits + carry := by
  induction digits generalizing carry with
  | nil => simp [ternaryDoubleDigitsAux, Nat.ofDigits]
  | cons digit digits ih =>
      have hdigit : digit < 3 := hdigits digit List.mem_cons_self
      have htail : ∀ d ∈ digits, d < 3 :=
        fun d hd => hdigits d (List.mem_cons_of_mem digit hd)
      have hnext := ternaryDoubleCarryStep_le_one carry digit
      have hlocal := ternaryDoubleCarryStep_local hcarry hdigit
      simp [ternaryDoubleDigitsAux, Nat.ofDigits, ih hnext htail]
      omega

lemma ternaryDoubleDigitsAux_sum_add_two_mul_carries
    {digits : List ℕ} {carry : ℕ} (hcarry : carry ≤ 1)
    (hdigits : ∀ digit ∈ digits, digit < 3) :
    (ternaryDoubleDigitsAux digits carry).sum +
        2 * ternaryDoubleCarryCountAux digits carry =
      2 * digits.sum + carry := by
  induction digits generalizing carry with
  | nil => simp [ternaryDoubleDigitsAux, ternaryDoubleCarryCountAux]
  | cons digit digits ih =>
      have hdigit : digit < 3 := hdigits digit List.mem_cons_self
      have htail : ∀ d ∈ digits, d < 3 :=
        fun d hd => hdigits d (List.mem_cons_of_mem digit hd)
      have hnext := ternaryDoubleCarryStep_le_one carry digit
      have hlocal := ternaryDoubleCarryStep_local hcarry hdigit
      have hrec := ih hnext htail
      simp [ternaryDoubleDigitsAux, ternaryDoubleCarryCountAux]
      omega

/-- Headline carry identity: Kummer's ternary digit excess is exactly twice
the number of carries generated by ternary doubling. -/
theorem ternaryDigitExcess_eq_two_mul_ternaryDoubleCarryCount (n : ℕ) :
    ternaryDigitExcess n =
      2 * ternaryDoubleCarryCount (Nat.digits 3 n) := by
  let output := ternaryDoubleDigitsAux (Nat.digits 3 n) 0
  have hdigits : ∀ digit ∈ Nat.digits 3 n, digit < 3 :=
    fun digit hdigit => Nat.digits_lt_base (by decide) hdigit
  have hlength : output.length = (Nat.digits 3 n).length + 1 := by
    simpa [output] using ternaryDoubleDigitsAux_length (Nat.digits 3 n) 0
  have hvalid : ∀ digit ∈ output, digit < 3 := by
    simpa [output] using
      (ternaryDoubleDigitsAux_lt_three
        (digits := Nat.digits 3 n) (carry := 0) (by decide) hdigits)
  have hvalue : Nat.ofDigits 3 output = 2 * n := by
    calc
      Nat.ofDigits 3 output =
          2 * Nat.ofDigits 3 (Nat.digits 3 n) + 0 := by
            simpa [output] using
              (ternaryDoubleDigitsAux_ofDigits
                (digits := Nat.digits 3 n) (carry := 0) (by decide) hdigits)
      _ = 2 * n := by simp [Nat.ofDigits_digits]
  have hsum : (Nat.digits 3 (2 * n)).sum = output.sum := by
    calc
      (Nat.digits 3 (2 * n)).sum =
          (Nat.digits 3 (Nat.ofDigits 3 output)).sum := by rw [hvalue]
      _ = output.sum :=
        Nat.sum_digits_ofDigits_eq_sum (by decide) ⟨hlength, hvalid⟩
  have hcarry :
      output.sum + 2 * ternaryDoubleCarryCount (Nat.digits 3 n) =
        2 * (Nat.digits 3 n).sum := by
    simpa [output, ternaryDoubleCarryCount] using
      (ternaryDoubleDigitsAux_sum_add_two_mul_carries
        (digits := Nat.digits 3 n) (carry := 0) (by decide) hdigits)
  unfold ternaryDigitExcess
  rw [hsum]
  omega

/-- Two ternary doubling carries imply divisibility of the central binomial
coefficient by nine. -/
theorem nine_dvd_centralBinom_of_two_le_ternaryDoubleCarryCount
    {n : ℕ} (h : 2 ≤ ternaryDoubleCarryCount (Nat.digits 3 n)) :
    9 ∣ Nat.centralBinom n := by
  haveI : Fact (Nat.Prime 3) := ⟨by decide⟩
  have hexcess : 4 ≤ ternaryDigitExcess n := by
    rw [ternaryDigitExcess_eq_two_mul_ternaryDoubleCarryCount]
    omega
  have hbound : (3 - 1) * 2 ≤
      2 * (Nat.digits 3 n).sum - (Nat.digits 3 (2 * n)).sum := by
    simpa [ternaryDigitExcess] using hexcess
  simpa using
    (pow_dvd_centralBinom_of_digit_excess (p := 3) (n := n) (e := 2) hbound)

/-- A universal carry certificate on nonexceptional powers of two would imply
the GKP conjecture. -/
theorem gkpConjecture_of_ternaryCarryCount
    (h : ∀ k : ℕ, 2 < k → k ≠ 6 → k ≠ 8 →
      2 ≤ ternaryDoubleCarryCount (Nat.digits 3 (2 ^ k))) :
    gkpConjecture := by
  apply gkpConjecture_of_powerOfTwo
  intro k hk2 hk6 hk8
  exact nine_dvd_centralBinom_of_two_le_ternaryDoubleCarryCount
    (h k hk2 hk6 hk8)

end GKPCarry
